before_script:
  - sed -i 's/<property name="javax.persistence.jdbc.password" value="postgres"\/>/<property name="javax.persistence.jdbc.password" value=""\/>' src/main/resources/META-INF/persistence.xml
  - psql -c 'create database meditec;' -U postgres

# after_script:
#   - mvn clean site -Ddependency.locations.enabled=false

language: java
