before_script:
  - sed -i 's/name="javax.persistence.jdbc.password" value=".*"/name="javax.persistence.jdbc.password" value=""/' src/main/resources/META-INF/persistence.xml
  - mysql -e 'create database meditec;' -u root

# after_script:
#   - mvn clean site -Ddependency.locations.enabled=false -DskipTests=true

jdk:
  - oraclejdk7

language: java
